config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  resources :users, only: [:new, :create, :update]
  resources :users, only: [:show], defaults: {format: :json}
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: {format: :json}  do
    get 'book/:id/reviews', :to => 'books#reviews'
    resources :books, only: [:create, :destroy, :show]
    resources :book_shelves, only: [:create, :index, :show, :destroy]
    resources :book_shelvings, only: [:create, :index, :show, :destroy]
    resources :reviews, only: [:create, :index, :destroy, :update, :show]
  end
end

app/views/shared/_form.html.erb
<% action_url = (action == :session_new) ? session_url : users_url %>
<% button_text = (action == :session_new) ? "Log In" : "Sign Up" %>

<div>
  <%= flash_errors %>
</div>

<div class="row">
  <div>
    <h1 class="sign-in-title">ShouldReads</h1>
  </div>
</div>

<form
  action="<%= action_url %>"
  class="form-horizontal log-in-form"
  method="post">
  <%= auth_token_input %>
  <div class="form-group">
    <input
      class="form-control"
      id="inputUsername"
      name="user[username]"
      placeholder="Username"
      type="text"
    >
  </div>
  <div class="form-group">
    <input
      type="password"
      class="form-control"
      id="inputPassword"
      placeholder="Password"
      name="user[password]"
    >
  </div>
  <div class="form-group">
    <% if button_text == "Log In" %>
      <button
        class="btn btn-primary btn-md btn-block log-in-button"
        type="submit"
      >
        Log In
      </button>
      <button
        class="btn btn-primary btn-md btn-block guest-button"
        type="submit"
      >
        Guest Log In
      </button>
    <% else %>
      <button
        class="btn btn-primary btn-md btn-block sign-up-button"
        type="submit"
      >
        Sign Up
      </button>
    <% end %>
  </div>
</form>

<script>
  $(".guest-button").on("click", function(event) {
    event.preventDefault();
    $("#inputUsername").val("guest");
    $("#inputPassword").val("password");
    $(".log-in-form").submit();
  });
</script>